- src/Dellucifer/README.md
- src/Dellucifer/weather.py
I used the Open Weather API to create this project and it's a beginner-friendly project in python. Basically, we are fetching weather details by passing an argument, which is place, to get the data and showing output.
> Added Weather Project using API

- src/vinayedula/Umbrella Reminder/README.md
- src/vinayedula/Umbrella Reminder/main.py
scrape weather data using Python and get reminders on email. If the weather condition is rainy or cloudy this program will send you an “umbrella reminder” to your email reminding you to pack an umbrella before leaving the house.  this program scrapes the weather information from Google using bs4 and requests libraries in python. 
Then based on the weather conditions this program sends the email using smtplib library. To run this program every day at a specified time i used the schedule library in python.
> Fix to  Issue # 6 

- src/Koredetaiwo/CreditCardValidator/README.md
- src/Koredetaiwo/CreditCardValidator/main.py
- [] My project uses dependencies
> Feat: CreditCardValidator #33

- src/illuricharles/Hacker-News-Data-Scraping/DataScraping.py
- src/illuricharles/Hacker-News-Data-Scraping/README.md
- src/illuricharles/Hacker-News-Data-Scraping/requirements.txt
Code will scrap the data from the hacker news website and store the data in seperate data folder in excel format.
> Hacker-News-Data-Scraping

- src/Money-20/BlackJack Game/README.md
- src/Money-20/BlackJack Game/blackjack.py
> Created BlackJack Game

- src/atharbeginner/EmailSender/README.md
- src/atharbeginner/EmailSender/main.py
- src/atharbeginner/EmailSender/requirements.txt
Created Python Script for Sending Email.
> Python script for sending email

- src/RAHULANUP/bubblesort/README.md
- src/RAHULANUP/bubblesort/bubblesort.py
Added python program for bubble sort........
> Added bubblesort in python

- src/RAHULANUP/drawpanda/README.md
- src/RAHULANUP/drawpanda/drawpanda.py
Drawing panda using turtle graphics in python........
> Added drawing panda using turtle

- src/atharbeginner/Mp3Player/README.md
- src/atharbeginner/Mp3Player/main.py
- src/atharbeginner/Mp3Player/requirements.txt
Signed-off-by: Athar Ali Khan <atharali.khan319@gmail.com>
> Python script for creating mp3 music player

- src/RAHULANUP/Radixsort/README.md
- src/RAHULANUP/Radixsort/Radixsort.py
Added radix sort in python........
> Added radix sort

- src/aishwarya0918/c_and_f_conversion.py
> Celcius to Fahrenheit and Fahrenheit to Celcius

- aishwarya0918/simpleinterest.py
> Simple Interest calculation

- src/aishwarya0918/multiples.py
> multiples.py

- src/aishwarya0918/factors.py
> factors.py

- src/aishwarya0918/simpleinterest.py
> simpleinterest.py

- src/RAHULANUP/binarysearch/README.md
- src/RAHULANUP/binarysearch/binarysearch.py
Added binary search in python........
> Added binary search

- src/SahityaSurpani/Pacman.py
> Added PacMan game

- src/Jagannath15/Check_Armstrong/main.py
#108 
I have added a folder(Jagannath15) with Armstrong Python program in it.
i have followed the all the rules.
- [ yes] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [ yes] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [no ] My project uses dependencies
- [ yes] I starred the repo
- [ yes] I had fun contributing!
please accept my PR . These my first ever contribution for hacktoberfest 2023. Thankyou.
> Issue No:108  : Added a program for hacktoberfest 2023

- src/akadeepesh/BounceBall/BounceBall.py
- src/akadeepesh/BounceBall/Readme.md
Added a tkinter BounceBall game with format specified 
- [yes ] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [yes ] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [no ] My project uses dependencies
- [ yes] I starred the repo
- [ yes] I had fun contributing!
> added a program of python

- src/asryan11/Tic_Tac_Toe/Readme.md
- src/asryan11/Tic_Tac_Toe/main.py
Developed Tic Tac Toe in Python with the random module.
- [yes ] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [ yes] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [ no] My project uses dependencies
- [ yes] I starred the repo
- [ yes] I had fun contributing!
> Added Tic Tac Toe in Python

- src/AnoshanJ/graphs/BFS.py
- src/AnoshanJ/graphs/DFS.py
- src/AnoshanJ/graphs/README.md
Added common graph algorithms (DFS, BFS) in python
> add DFS and BFS

- src/AnoshanJ/webscraping/README.md
- src/AnoshanJ/webscraping/requirements.txt
- src/AnoshanJ/webscraping/wiki_scrape.py
Implemented webscraping of Wikipedia using python and beautifulsoap
> add webscraping

- src/Master-Keshav/Python Password Generator/Readme.md
- src/Master-Keshav/Python Password Generator/password_generator.py
- src/Master-Keshav/Python Password Generator/requirements.txt
1) Password generation: The script generates random passwords with customizable length and complexity.
2) Display the generated password to the user.
3) Allow the user to specify password length and complexity (e.g., uppercase, lowercase, numbers, special characters).
4) A user-friendly command-line interface.
> feat: Added Password Generator (Issue #139)

- src/Master-Keshav/Python Expense Tracker/Readme.md
- src/Master-Keshav/Python Expense Tracker/expense_tracker.py
- src/Master-Keshav/Python Expense Tracker/requirements.txt
Features:
1) Expense tracking: Users can add, view, and categorize their expenses.
2) Categories: Expenses can be categorized into different types (e.g., groceries, entertainment, bills).
3) Expense insights: Provide statistics and insights into spending patterns, such as total spending per category, monthly expenses, and average daily spending.
4) Persistence: Allow users to save their expense data to a file for future reference.
5) User-friendly command-line interface or a simple GUI.
> feat: Adding Expense Tracker (Issue #141)

- src/Master-Keshav/Task Manager/Readme.md
- src/Master-Keshav/Task Manager/requirements.txt
- src/Master-Keshav/Task Manager/task_manager.py
Features:
1) Task Management: Users can add, update, and organize tasks into categories.
2) To-Do List: Maintain a list of to-do items with descriptions and due dates.
3) Task Insights: Provide statistics on completed tasks, overdue tasks, and tasks by category.
4) Task Persistence: Allow users to save their task data to a file for future reference.
5) User-friendly command-line interface or a simple GUI.
> feat: Added Task Manager with To-Do List (Issue #142)

- src/asryan11/Dice_Roller/README.md
- src/asryan11/Dice_Roller/main.py
I have added a Python script by which we can roll two dice to get random numbers.
- [ yes] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [yes ] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [yes] My project uses dependencies
- [ yes] I starred the repo
- [ yes] I had fun contributing!
> Added Dice Roller in Python

- src/JuanitaCathy/URL Shortener/requirements.txt
- src/JuanitaCathy/URL Shortener/shortener.py
The python script takes a long URL as input and  makes use of the 'pyshorteners' library.
> URL Shortener

- src/harshpreet931/All Sorting Algorithms/BitonicSort.py
- src/harshpreet931/All Sorting Algorithms/BubbleSort.py
- src/harshpreet931/All Sorting Algorithms/CombSort.py
- src/harshpreet931/All Sorting Algorithms/CountingSort.py
- src/harshpreet931/All Sorting Algorithms/CycleSort.py
- src/harshpreet931/All Sorting Algorithms/GnomeSort.py
- src/harshpreet931/All Sorting Algorithms/HeapSort.py
- src/harshpreet931/All Sorting Algorithms/InsertionSort.py
- src/harshpreet931/All Sorting Algorithms/MergeSort.py
- src/harshpreet931/All Sorting Algorithms/OddEvenSort.py
- src/harshpreet931/All Sorting Algorithms/PanCakeSort.py
- src/harshpreet931/All Sorting Algorithms/QuickSort.py
- src/harshpreet931/All Sorting Algorithms/RadixSort.py
- src/harshpreet931/All Sorting Algorithms/SelectionSort.py
- src/harshpreet931/All Sorting Algorithms/ShellSort.py
- src/harshpreet931/All Sorting Algorithms/StoogeSort.py
_# Fix to  Issue # 
===============================_
**Added Python Scripts for All General Sorting Algorithms**
- [yes] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [yes ] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [no] My project uses dependencies
- [yes] I starred the repo
- [yes] I had fun contributing!
> Added All Sorting Algorithms

- src/sulavmhrzn/random_password_generator/main.py
> random password generator

- src/gh-adithya/Mail Merge Project/Input/Letters/starting_letter.txt
- src/gh-adithya/Mail Merge Project/Input/Names/invited_names.txt
- src/gh-adithya/Mail Merge Project/README.md
- src/gh-adithya/Mail Merge Project/main.py
- src/gh-adithya/Mail Merge Project/requirements.txt
=========================================================================
Added a Mail Merge project that auto-generates letters using a template, and with names provided. 
=========================================================================
> Add main.py, requirements.txt and README.md for Mail Merge

- src/sulavmhrzn/rock_paper_scissor/main.py
> rock paper scissor

- src/harshpreet931/BasicPrograms/033_AverageOfNumbers.py
- src/harshpreet931/BasicPrograms/034_PerfectNumber.py
- src/harshpreet931/BasicPrograms/035_IntersectionOf2Lists.py
- src/harshpreet931/BasicPrograms/036_KmToMi.py
- src/harshpreet931/BasicPrograms/037_PerfectSquare.py
- src/harshpreet931/BasicPrograms/038_UnionOf2Lists.py
- src/harshpreet931/BasicPrograms/039_FtToM.py
- src/harshpreet931/BasicPrograms/040_PrimeFactors.py
- src/harshpreet931/BasicPrograms/041_BinaryToDecimal.py
- src/harshpreet931/BasicPrograms/042_Median.py
- src/harshpreet931/BasicPrograms/043_StandardDivision.py
- src/harshpreet931/BasicPrograms/044_Mode.py
- src/harshpreet931/BasicPrograms/045_DecimalToOctal.py
- src/harshpreet931/BasicPrograms/046_ArmstrongNumberInARange.py
- src/harshpreet931/BasicPrograms/047_CountVowelsAndConsonats.py
- src/harshpreet931/BasicPrograms/048_Anagrams.py
- src/harshpreet931/BasicPrograms/049_LongesCommonPrefix.py
- src/harshpreet931/BasicPrograms/050_AreaOfTriangle.py
- src/harshpreet931/BasicPrograms/051_ListOfPrimes.py
- src/harshpreet931/BasicPrograms/052_ShuffleADeckOfCards.py
- src/harshpreet931/BasicPrograms/053_Pangram.py
- src/harshpreet931/BasicPrograms/054_SumOfDigits.py
- src/harshpreet931/BasicPrograms/055_DecimalToHexadecimal.py
- src/harshpreet931/BasicPrograms/056_PerimeterOfARect.py
- src/harshpreet931/BasicPrograms/057_EvenOrOdd.py
- src/harshpreet931/BasicPrograms/058_SumOfSquares.py
- src/harshpreet931/BasicPrograms/059_FindTheASCIIValue.py
- src/harshpreet931/BasicPrograms/060_LCD.py
_# Fix to  Issue # 
===============================_
**Added 33 to 60 Python Basic Programs.**
- [yes] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [yes] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [] My project uses dependencies
- [yes] I starred the repo
- [yes] I had fun contributing!
> Added Python Basic Programs 33-60

- src/Nikunj Navdiya/Discord bot/README.md
- src/Nikunj Navdiya/Discord bot/discord.py
- src/Nikunj Navdiya/Discord bot/requirements.txt
I have added a simple python discord bot script which responds to your message. I have used PALM AI over here to generate response.
> Added Simple responding discord bot python script

- src/sulavmhrzn/basic_web_server/main.py
- src/sulavmhrzn/insertion_sort/main.py
> basic web server

- src/Jacintomuambumba/password generator #167/Generator.py
- src/Jacintomuambumba/password generator #167/README.md
The "Password Generator in Python" is a simple utility that generates random passwords with a user-friendly graphical interface. This project serves the purpose of creating strong, randomized passwords, which can be used for improved security in various applications.
- [ x] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [x ] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [ x] My project uses dependencies
- [x ] I starred the repo
Team Codev
@aoscode
#aoscode
#aosccode
> Password generator

- src/sulavmhrzn/bubble_sort/main.py
> bubble sort

- src/harshpreet931/BasicPrograms/061_FileSize.py
- src/harshpreet931/BasicPrograms/062_AutomorphicNumber.py
- src/harshpreet931/BasicPrograms/063_SumOfCubes.py
- src/harshpreet931/BasicPrograms/064_NoOfWordsInAString.py
- src/harshpreet931/BasicPrograms/065_DisariumNumber.py
- src/harshpreet931/BasicPrograms/066_AreaOfAParallelogram.py
- src/harshpreet931/BasicPrograms/067_FactorsOfANumber.py
- src/harshpreet931/BasicPrograms/068_PerimeterOfCircle.py
- src/harshpreet931/BasicPrograms/069_NivenNumber.py
- src/harshpreet931/BasicPrograms/070_ListOfFibonacci.py
- src/harshpreet931/BasicPrograms/071_AbundantNumber.py
- src/harshpreet931/BasicPrograms/072_AreaOfASector.py
- src/harshpreet931/BasicPrograms/073_ListOfPalindromeNumbers.py
- src/harshpreet931/BasicPrograms/074_PerimeterOfASquare.py
- src/harshpreet931/BasicPrograms/075_NeonNumber.py
- src/harshpreet931/BasicPrograms/076_AreaOfRhombus.py
- src/harshpreet931/BasicPrograms/077_SmithNumber.py
- src/harshpreet931/BasicPrograms/078_HypotenuseOfARightTriangle.py
- src/harshpreet931/BasicPrograms/079_SpyNumber.py
- src/harshpreet931/BasicPrograms/080_VolumeOfACylinder.py
_# Fix to  Issue # 
===============================_
**Added 61-80 Programs**
- [yes] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [yes] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [yes] My project uses dependencies
- [yes] I starred the repo
- [yes] I had fun contributing!
> Added 61-80 programs

- src/harshpreet931/BasicPrograms/0100_EmirpPrime.py
- src/harshpreet931/BasicPrograms/081_DuckNumber.py
- src/harshpreet931/BasicPrograms/082_AreaOfEllipse.py
- src/harshpreet931/BasicPrograms/083_PronicNumber.py
- src/harshpreet931/BasicPrograms/084_VolumeOfASphere.py
- src/harshpreet931/BasicPrograms/085_TriangularNumber.py
- src/harshpreet931/BasicPrograms/086_VolumeOfACone.py
- src/harshpreet931/BasicPrograms/087_MagicNumber.py
- src/harshpreet931/BasicPrograms/088_SurfaceAreaOfACube.py
- src/harshpreet931/BasicPrograms/089_HappyNumber.py
- src/harshpreet931/BasicPrograms/090_CubeNumber.py
- src/harshpreet931/BasicPrograms/091_MaximumSubarraySum.py
- src/harshpreet931/BasicPrograms/092_GCP.py
- src/harshpreet931/BasicPrograms/093_HappyPrimeNumber.py
- src/harshpreet931/BasicPrograms/094_IntersectionOfMultipleLists.py
- src/harshpreet931/BasicPrograms/095_MedianOfAList.py
- src/harshpreet931/BasicPrograms/096_LCMofMultipleNumbers.py
- src/harshpreet931/BasicPrograms/097_NthFibonacci.py
- src/harshpreet931/BasicPrograms/098_AreaOfRegularPolygon.py
- src/harshpreet931/BasicPrograms/099_PascalsTriangle.py
_# Fix to  Issue # 
===============================_
**Added 81-100 Programs.**
- [yes] I read the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [yes] I structured my project as stated in the [contributing guidelines](https://github.com/theadeyemiolayinka/python-scripts/blob/main/contributing.md)
- [] My project uses dependencies
- [yes] I starred the repo
- [yes] I had fun contributing!
> Added 81-100 Programs

- src/Shreya111111/passwordcipher/README.md
- src/Shreya111111/passwordcipher/pass.py
Password cipher strength generator
It does by checking the number of letters, numbers, special characters, and whitespace characters within a given password and generating a score based on these results.
> password strength checker

- src/Shreya111111/automail/README.md
- src/Shreya111111/automail/automail.py
- src/Shreya111111/passwordcipher/README.md
- src/Shreya111111/passwordcipher/pass.py
Customer Support: Auto-reply to common customer queries and issues with automated responses
> automail generation

- src/lukman155/todo-list/Readme.md
- src/lukman155/todo-list/main.py
This is a command line interface todo list where you can create, edit, and view todos.
> Add: TodoList

- src/lukman155/password-generator/Readme.md
- src/lukman155/password-generator/main.py
- src/lukman155/todo-list/Readme.md
This is an advanced password generator script written in Python. It allows you to generate strong and customizable passwords for various purposes.
> Add: Pass-Gen and Fix Todo Readme
